#ifndef SAL_H_MOCK
#define SAL_H_MOCK

#define _In_
#define _Out_
#define _Inout_
#define _In_opt_
#define _Out_opt_
#define _Inout_opt_
#define _In_reads_(x)
#define _Out_writes_(x)
#define _Inout_updates_(x)
#define _In_reads_bytes_(x)
#define _Out_writes_bytes_(x)
#define _Inout_updates_bytes_(x)
#define _In_reads_opt_(x)
#define _Out_writes_opt_(x)
#define _Inout_updates_opt_(x)
#define _In_reads_bytes_opt_(x)
#define _Out_writes_bytes_opt_(x)
#define _Inout_updates_bytes_opt_(x)
#define _Out_writes_to_(x,y)
#define _Out_writes_bytes_to_(x,y)
#define _Inout_updates_to_(x,y)
#define _Inout_updates_bytes_to_(x,y)
#define _Out_writes_to_opt_(x,y)
#define _Out_writes_bytes_to_opt_(x,y)
#define _Inout_updates_to_opt_(x,y)
#define _Inout_updates_bytes_to_opt_(x,y)
#define _Outptr_
#define _Outptr_opt_
#define _Outptr_result_maybenull_
#define _Outptr_opt_result_maybenull_
#define _Outref_
#define _Outref_result_maybenull_
#define _Outptr_result_buffer_(x)
#define _Outptr_opt_result_buffer_(x)
#define _Outptr_result_buffer_to_(x,y)
#define _Outptr_opt_result_buffer_to_(x,y)
#define _Outptr_result_bytebuffer_(x)
#define _Outptr_opt_result_bytebuffer_(x)
#define _Outptr_result_bytebuffer_to_(x,y)
#define _Outptr_opt_result_bytebuffer_to_(x,y)
#define _Printf_format_string_
#define _Scanf_format_string_
#define _Scanf_s_format_string_
#define _In_z_
#define _Out_z_
#define _Inout_z_
#define _In_opt_z_
#define _Out_opt_z_
#define _Inout_opt_z_
#define _In_reads_z_(x)
#define _Out_writes_z_(x)
#define _Inout_updates_z_(x)
#define _In_reads_opt_z_(x)
#define _Out_writes_opt_z_(x)
#define _Inout_updates_opt_z_(x)
#define _Success_(x)
#define _Return_type_success_(x)
#define _On_failure_(x)
#define _Ret_maybenull_
#define _Ret_notnull_
#define _Ret_z_
#define _Ret_maybenull_z_
#define _Ret_notnull_z_
#define _Field_size_(x)
#define _Field_size_opt_(x)
#define _Field_size_bytes_(x)
#define _Field_size_bytes_opt_(x)
#define _Field_size_part_(x,y)
#define _Field_size_part_opt_(x,y)
#define _Field_size_bytes_part_(x,y)
#define _Field_size_bytes_part_opt_(x,y)
#define _Field_size_full_(x)
#define _Field_size_full_opt_(x)
#define _Field_size_bytes_full_(x)
#define _Field_size_bytes_full_opt_(x)
#define _Struct_size_bytes_(x)

#endif
